{% set name = "autogluon.features" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/0.8.3_patch/tarball.tar.gz 
  sha256: 1ccc6834b753ad0dc1d96338d8d56ada5b86356a2d34a9e2a29c3e685af277e1 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./features -vv
  number: 1
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  # see deps in https://github.com/autogluon/autogluon/blob/master/features/setup.py
  # version bounds defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >=3.8,<3.11
    - numpy >=1.21,<1.27
    - pandas >=1.4.1,<2.2
    - scikit-learn >=1.1,<1.5
    - autogluon.common =={{ version }}
    - packaging

test:
  imports:
    - autogluon.features
  commands:
    - python -c "from autogluon.features import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'" 
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.features/
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
    - prateekdesai04
