{% set name = "autogluon.features" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42e4838bb95328cedb54a9d094072068d8ce1e610a1154f91190b3670011561b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./features -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python {{ python_min }}
    - pip
  # see deps in https://github.com/autogluon/autogluon/blob/master/features/setup.py
  # version bounds defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.25.0,<2.4.0
    - pandas >=2.0.0,<2.4.0
    - scikit-learn >=1.4.0,<1.8.0
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.features
  commands:
    - python -c "from autogluon.features import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.features/
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong
    predictive performance in your applications. With just a few lines of code, you
    can train and deploy high-accuracy machine learning and deep learning models on
    image, text, time series, and tabular data.
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - Innixma
    - prateekdesai04
